### ISSUE TITLE
Sometime some custom player head and player in inventory cut off

### ISSUE THREAD

**Issue by futag** [FxMorin/MoreCulling#286]
![MoreCulling 0.26.0 + 3D Skin Layers 1.6.7](https://github.com/user-attachments/assets/c9f02c51-dd1e-466d-8733-fded60667ddb)
> MoreCulling 0.26.0 + [3D Skin Layers 1.6.7](https://modrinth.com/mod/3dskinlayers) (Part of the skin layer is cut / missing)

![2024-09-02_19 43 26](https://github.com/user-attachments/assets/cb09396e-2938-4fa1-91a9-4402569147ef)
> MoreCulling 0.27.*  (More layer cutting / missing)

**Comment by NerdSkape** [comment]
I'm having the same issue as well. I can't explain why it is happening. If I do a fresh install of just More Culling, Fabric API and Cloth Config API, there is no issue. 

If I install the Simply Optimized mod pack the issue appears. I figured it must be a mod compatibility issue so I disabled every mod except More Culling, Fabric API and Cloth Config API, but the issue still happens. 

I figured that launching before disabling the mod must have caused the issue so I made another clean install of Simply Optimized and disable every mod except More Culling, Fabric API and Cloth Config API, but the problem still happens.

It makes zero sense to me why installing each mod individually works fine, but installing it as part of a mod pack and disabling everything else still causes the issue.

Since I was using Modrinth as my launcher, I tried using the repair instance option but that also did not fix the issue.

As a last test, I took the moreculling.toml from the config folder on a clean install where the mods were manually loaded and everything looked fine and copied to an instance where the issue was present. This time the problem was no longer present.

After comparing the config files I noticed entityModelCulling = true even though sodium was present and the mod claimed it was disabled when viewing the option in game. It appears the problem is the mod failing to set entityModelCulling = false when sodium is installed. Manually editing the config file to false resolves the issue.

**Comment by futag** [comment]
> I'm having the same issue as well. I can't explain why it is happening. If I do a fresh install of just More Culling, Fabric API and Cloth Config API, there is no issue.
> 
> If I install the Simply Optimized mod pack the issue appears. I figured it must be a mod compatibility issue so I disabled every mod except More Culling, Fabric API and Cloth Config API, but the issue still happens.
> 
> I figured that launching before disabling the mod must have caused the issue so I made another clean install of Simply Optimized and disable every mod except More Culling, Fabric API and Cloth Config API, but the problem still happens.
> 
> It makes zero sense to me why installing each mod individually works fine, but installing it as part of a mod pack and disabling everything else still causes the issue.
> 
> Since I was using Modrinth as my launcher, I tried using the repair instance option but that also did not fix the issue.
> 
> As a last test, I took the moreculling.toml from the config folder on a clean install where the mods were manually loaded and everything looked fine and copied to an instance where the issue was present. This time the problem was no longer present.
> 
> After comparing the config files I noticed entityModelCulling = true even though sodium was present and the mod claimed it was disabled when viewing the option in game. It appears the problem is the mod failing to set entityModelCulling = false when sodium is installed. Manually editing the config file to false resolves the issue.

I got it, i deleted more culling config, and issue is fixed
