### ISSUE TITLE
Mod seems to have caused a crash

### ISSUE THREAD

**Issue by YumatanGames** [fxmorin/MoreCulling#4]
Hi, I was testing this mod earlier, using the latest version of Fabulously Optimized (3.9.0). Although I did notice a massive performance boost, it crashed my game after a while playing. I was playing for well over an hour when the came crashed with Not Enough Crashes pointing it as the culprit. 

I immediately tried to log back into the world and I crashed again, with Not Enough Crashes now saying the problem was with Iris. 

I'll be pasting both logs here:
[crash-2022-06-04_00.35.08-client.txt](https://github.com/fxmorin/MoreCulling/files/8837017/crash-2022-06-04_00.35.08-client.txt)
[crash-2022-06-04_00.35.21-client.txt](https://github.com/fxmorin/MoreCulling/files/8837018/crash-2022-06-04_00.35.21-client.txt)
 

I hope this help you figure it out, cause the performance boost I was having with this mod was really impressive.

**Comment by JumperCzech** [comment]
Same thing happened to me while I was testing flying machines, funnily enough I accidentally created one that can consistently cause the crash so hopefully that helps narrow it down.
It only happens when the machine goes in the direction towards the honey blocks.

Here's how to build one by layers.
![crashy machine](https://user-images.githubusercontent.com/83337894/171993465-78461837-3776-46a2-9fc0-10444a341962.png)

Here is schematic
https://mega.nz/file/3hIQkRjY#J1gkVpoidkCZXpL_mIWJZf_GsVTyXZqJsjAZRFthpI4
and structure file
https://mega.nz/file/mohDGCgK#V0vxP57fXob7f9HFwMK4UukUooFgzxvN7thhEjRfbFo
if you prefer those.

**Comment by fxmorin** [comment]
Next version already fixes this issue. Should be out soon
